dist: trusty
sudo: required

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 8

before_script:
  - npm install babel-preset-medopad --no-save
