env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 8

before_script:
  - npm install babel-preset-medopad --no-save
  - curl -o ./node_modules/eslint-plugin-react/lib/rules/jsx-curly-spacing.js "https://raw.githubusercontent.com/jseminck/eslint-plugin-react/75fb917c1ce27540f48cbe3fa7436a6822d4b953/lib/rules/jsx-curly-spacing.js"

deploy:
  provider: npm
  email: bobby.biran@medopad.com
  api_key:
    secure: rAk0wPp28SPwZamAttx7C843m9dBTpKxbwHL1+cYMNTL5aDCul1O4FRfT4CxsENQHupa+BTrUlnaVxET6kaY8l0tmCUhNm87Dj8g0SZQ1mOBROYTmteHSXIwk8HMXHOR610cUw/XUPo0W06qdc7ZpgvdmWrM4vV/8z5l02nuAyGXsV7GUxeTOE6Zb69YDUaduojHWOmt6Vioo1Glr/UEP6fe01doXE55uNqvBJQhb4N0/7RrAW3At1yC2lODJgI12LLm02awRYYSYb0XXunx9rJN5IZq3/OTrrnmRFEYsxLgQcwYqkiFKDe7+OdQ2ly2eVfHA0DUcIsepsJofZewBLyqBC5Ks6xm5rqG2+oi65fm+lROeRSyZFvs8Z9eFaITLljEVBTqV4yK1WWXVJCQrNnduqFXhl/t9AwsHWmPMPLudnfYy91JlZL9mF+KKHNh2QjQVXuv90qEKrxK+aHxFg9rsO/9GyNIT6sggLiztIhmkcsn7Xiewr2dEW6uu2NkloG4ghqxYo0SKPue1ZTx9PhllC9a56LR9J34YggOFRsT691s/bCJCK17RBmSN7K720An9sEqhbIxOyXwsxcLvEvpO6p9CHU9ee0qDL5/7mLABGzP2g93qMqI53iWsxtxaAh454OemUXBHYJXMhfOhdY+4gDuKz81mbeMPBX9bM4=
  on:
    tags: true
    repo: Medopad/babel-preset-medopad-react
